// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeKvvx4yU4Mhf6Lq7qf8rPcZihf_xNUkI',
    appId: '1:93868432068:android:6dfe7b4ec8cd4d72638791',
    messagingSenderId: '93868432068',
    projectId: 'soundofmeme-4ca57',
    storageBucket: 'soundofmeme-4ca57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPm5rfXoJoPfM65WHUOgRno0Sr_q0_oPg',
    appId: '1:93868432068:ios:cc062d90343662d7638791',
    messagingSenderId: '93868432068',
    projectId: 'soundofmeme-4ca57',
    storageBucket: 'soundofmeme-4ca57.appspot.com',
    androidClientId: '93868432068-55auhbl5msuahafl8sqvf94rvhjrisb6.apps.googleusercontent.com',
    iosClientId: '93868432068-jj5ng8rr3tla4kco6m6qh83l7n9fg4fo.apps.googleusercontent.com',
    iosBundleId: 'com.example.soundofmemenew',
  );
}
